# Generated by Django 4.0.6 on 2023-02-09 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0030_alter_storywatches_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storywatches',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched', to='djapp.story'),
        ),
        migrations.AlterField(
            model_name='storywatches',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
