# Generated by Django 4.0.6 on 2023-02-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0034_story_mediatype'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='file2',
            field=models.FileField(blank=True, upload_to='media/posts'),
        ),
        migrations.AddField(
            model_name='posts',
            name='file3',
            field=models.FileField(blank=True, upload_to='media/posts'),
        ),
        migrations.AddField(
            model_name='posts',
            name='mediatype2',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='posts',
            name='mediatype3',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='posts',
            name='zfile',
            field=models.FileField(blank=True, upload_to='uploads/zpostfile'),
        ),
    ]
