# Generated by Django 4.0.6 on 2023-02-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0035_posts_file2_posts_file3_posts_mediatype2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
