# Generated by Django 4.0.6 on 2023-02-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djadmin', '0005_postreports_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='postreports',
            name='opt',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
