# Generated by Django 4.0.6 on 2023-02-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djadmin', '0006_postreports_opt'),
    ]

    operations = [
        migrations.AddField(
            model_name='postreports',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
