# Generated by Django 4.0.6 on 2023-02-04 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0029_rename_is_verfied_user_is_verified'),
        ('djadmin', '0007_postreports_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostReportsCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_reports', models.IntegerField()),
                ('most_reason', models.IntegerField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djapp.posts')),
            ],
        ),
    ]
