# Generated by Django 4.0.6 on 2023-02-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djadmin', '0008_postreportscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postreportscount',
            name='most_reason',
            field=models.IntegerField(null=True),
        ),
    ]
